baseurl = "http://www.neuralnuance.com/"
title = "NeuralNuance"
languageCode = "en-us"


[Params]
TitleAppendix = " - www.neuralnuance.com"
Description = "NeuralNuance by Alex H. Raber"
Keywords = "Neural, Nuance, Alex H. Raber, Raber, Alex, Developer"
